locais = {
    'a1' : {'nome' : 'corredor1' , 'sul' : 'b1' , 'leste' : 'a2'}, 
    'a2' : {'nome' : 'corredor2' , 'oeste' : 'a1' , 'leste' : 'a3'} , 
    'a3' : {'nome' : 'quarto' , 'oeste' : 'a2' , 'item' : 'escudo'} , 
    'a4' : {'nome' : 'corredor3' , 'sul' : 'b4' , 'leste' : 'a5'} , 
    'a5' : {'nome' : 'saída' , 'oeste' : 'a4'} , 
    'b1' : {'nome' : 'corredor4' , 'norte' : 'a1' , 'sul' : 'c1'} , 
    'b4' : {'nome' :'corredor5' , 'oeste' : 'c2' , 'norte' : 'a4'} , 
    'b5' : {'nome' : 'quarto' , 'sul' : 'c5' , 'inimigo' : 'monstro' , 'item' : 'poção'} , 
    'c1' : {'nome' : 'corredor6' , 'norte' : 'b1' , 'sul' : 'd1' , 'leste' : 'c2' , 'inimigo' : 'monstro superior'} , 
    'c2' : {'nome' : 'salão principal' , 'oeste' : 'c1' , 'leste' : 'b4' , 'inimigo' : 'O CHEFÃO' , 'item' : 'chave'} , 
    'c4' : {'nome' : 'corredor7' , 'sul' : 'd4' , 'leste' : 'c5'} , 
    'c5' : {'nome' : 'corredor8' , 'norte' : 'b5' , 'oeste' : 'c4' , 'sul' : 'd5'} , 
    'd1' : {'nome' : 'corredor9' , 'norte' : 'c1' , 'sul' : 'e1' , 'leste' : 'd2'} , 
    'd2' : {'nome' : 'corredor10' , 'leste' : 'd3' , 'oeste' : 'd1' , 'sul' : 'e2'} , 
    'd3' : {'nome' : 'corredor11' , 'oeste' : 'd2' , 'leste' : 'd4' , 'sul' : 'e3'} , 
    'd4' : {'nome' : 'corredor12' , 'oeste' : 'd3' , 'norte' : 'c4'} , 
    'd5' : {'nome' : 'corredor13' , 'norte' : 'c5' , 'sul' : 'e5'} , 
    'e1' : {'nome' : 'quarto' , 'norte' : 'd1' , 'inimigo' : 'monstro'} , 
    'e2' : {'nome' : 'corredor14' , 'norte' : 'd2' , 'sul' : 'f2'} , 
    'e3' : {'nome' : 'corredor15' , 'norte' : 'd3' , 'sul' : 'f3' , 'leste' : 'e4'} , 
    'e4' : {'nome' : 'corredor16' , 'oeste' : 'e3' , 'sul' : 'f4'} , 
    'e5' : {'nome' : 'depósito' , 'norte' : 'd5'} , 
    'f1' : {'nome' : 'escritório' , 'leste' : 'f2'} , 
    'f2' : {'nome' : 'corredor17' , 'oeste' : 'f1' , 'norte' : 'e2'} , 
    'f3' : {'nome' : 'corredor18' , 'oeste' : 'f2' , 'norte' : 'e3'} , 
    'f4' : {'nome' : 'corredor19' , 'norte' : 'e4' , 'leste' : 'f5'} , 
    'f5' : {'nome' : 'quarto' , 'oeste' : 'f4'}}locais = {'a1' : {'nome' : 'corredor1' , 'sul' : 'b1' , 'leste' : 'a2'}
 , 
'a2' : {'nome' : 'corredor2' , 'oeste' : 'a1' , 'leste' : 'a3'} , 
'a3' : {'nome' : 'quarto' , 'oeste' : 'a2' , 'item' : 'escudo'} , 
'a4' : {'nome' : 'corredor3' , 'sul' : 'b4' , 'leste' : 'a5'} , 
'a5' : {'nome' : 'saída' , 'oeste' : 'a4'} , 
'b1' : {'nome' : 'corredor4' , 'norte' : 'a1' , 'sul' : 'c1'} , 
'b4' : {'nome' :'corredor5' , 'oeste' : 'c2' , 'norte' : 'a4'} , 
'b5' : {'nome' : 'quarto' , 'sul' : 'c5' , 'inimigo' : 'monstro' , 'item' : 'poção'} , 
'c1' : {'nome' : 'corredor6' , 'norte' : 'b1' , 'sul' : 'd1' , 'leste' : 'c2' , 'inimigo' : 'monstro superior'} , 
'c2' : {'nome' : 'salão principal' , 'oeste' : 'c1' , 'leste' : 'b4' , 'inimigo' : 'O CHEFÃO' , 'item' : 'chave'} , 
'c4' : {'nome' : 'corredor7' , 'sul' : ''d4' , 'leste' : 'c5'} , 
'c5' : {'nome' , 'corredor8' , 'norte' : 'b5' , 'oeste' : 'c4' , 'sul' :' ''d'5'} , 
'd1' : {'nome' : 'corredor9' , 'norte' : 'c1' , 'sul' : 'e1' , 'leste' : 'd2'} , 
'd2' : {'nome' : 'corredor10' , 'leste' : ''''' , 'oeste' : 'd1' , 'sul' : e2} , 
'd3' :' {'nome' : 'corredor11' , 'oetse' : d2' ,' 'leste' : 'd4' ,' 'sul' : e3} , 
''d4 :' {''nome' : 'corredor12' , 'oeste' : ''' ,' ''norte' : c4} ',' ''
d5 :' {''nome' : 'corredor13' , 'norte' : c5 ,' ''sul' : e5} , 
'e1 : {''n'ome' : 'quarto' , 'norte' : d1 , ''in'imigo' : 'monstro'} , 
e2 : {'nome' : 'corredor14' , 'norte' : d2 , 'su'l'' : f2} , 
e3 : {'nome' : 'corredor15' , 'norte' : ''' , 'sul' :' f'3 , 'leste' : e4} , 
e4 : {'nome' : 'corredor16' , 'oeste' : e3 , 'sul' : f4} , 
e5 : {'nome' : 'depósito' , 'norte'' :' d5} , 
f1 : {'nome' : 'e'sc'ritório' , 'leste' : f2} , 
f2 : {'nome' : 'corredor17' , 'oeste' : f1 , 'norte' : e2} , 
f3 : {'nome' : 'corredor18' , 'oeste' : f2 , 'norte' : e3} , 
f4 : {'nome' : 'corredor19' , 'norte' : e4 , 'leste' : f5} , 
f5 : {'nome' , 'quarto' , 'oeste' : f4}}